#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
#include "SupportCanvas3D.h"
#include "Databinding.h"

class View;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

    void dataBind();

private slots:
    void openFileScene();

    // Used internally to keep data bindings and the user interface in sync.
    void settingsChanged();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;
    SupportCanvas3D *m_canvas3D;

    QList<DataBinding*> m_bindings;




};

#endif // MAINWINDOW_H
